// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Heart.Message {

  /// <summary>Holder for reflection information generated from message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tZXNzYWdlLnByb3RvEg1IZWFydC5NZXNzYWdlItsCCgdUZXN0TXNnEgkK",
            "AWEYASABKAISCQoBYhgCIAEoBRIJCgFjGAMgASgDEgkKAWQYBCABKAkSCQoB",
            "ZRgFIAEoCBITCgt0ZXN0Rml4ZWQzMhgGIAEoBxITCgt0ZXN0Rml4ZWQ2NBgH",
            "IAEoBhIUCgx0ZXN0U0ZpeGVkMzIYCCABKA8SFAoMdGVzdFNGaXhlZDY0GAkg",
            "ASgQEhEKCXRlc3RCeXRlcxgKIAEoDBIZCgx0ZXN0T3B0aW9uYWwYCyABKAVI",
            "AYgBARIJCgFmGAwgAygFEigKAWcYDSADKAsyHS5IZWFydC5NZXNzYWdlLlRl",
            "c3RNc2cuR0VudHJ5EgsKAWgYDiABKAVIABILCgFpGA8gASgJSAAaKAoGR0Vu",
            "dHJ5EgsKA2tleRgBIAEoBRINCgV2YWx1ZRgCIAEoCToCOAFCCwoJdGVzdE9u",
            "ZW9mQg8KDV90ZXN0T3B0aW9uYWwijwEKCFRlc3RNc2cyEicKB3Rlc3RNc2cY",
            "ASABKAsyFi5IZWFydC5NZXNzYWdlLlRlc3RNc2cSKQoIdGVzdEVudW0YAiAB",
            "KA4yFy5IZWFydC5NZXNzYWdlLlRlc3RFbnVtEikKCHRlc3RNc2cyGAMgASgL",
            "MhcuSGVhcnQuTWVzc2FnZS5UZXN0TXNnMkoECBYQFyJgCghUZXN0TXNnMxIp",
            "Cgh0ZXN0TXNnMhgBIAEoCzIXLkhlYXJ0Lk1lc3NhZ2UuVGVzdE1zZzISKQoI",
            "dGVzdE1zZzMYAiABKAsyFy5IZWFydC5NZXNzYWdlLlRlc3RNc2czKjcKCFRl",
            "c3RFbnVtEg0KCVRFU1RFTlVNMRAAEg0KCVRFU1RFTlVNMhABEg0KCVRFU1RF",
            "TlVNMxACQhP4AQGqAg1IZWFydC5NZXNzYWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Heart.Message.TestEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Heart.Message.TestMsg), global::Heart.Message.TestMsg.Parser, new[]{ "A", "B", "C", "D", "E", "TestFixed32", "TestFixed64", "TestSFixed32", "TestSFixed64", "TestBytes", "TestOptional", "F", "G", "H", "I" }, new[]{ "TestOneof", "TestOptional" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Heart.Message.TestMsg2), global::Heart.Message.TestMsg2.Parser, new[]{ "TestMsg", "TestEnum", "TestMsg2_" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Heart.Message.TestMsg3), global::Heart.Message.TestMsg3.Parser, new[]{ "TestMsg2", "TestMsg3_" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///规则九 枚举
  /// </summary>
  public enum TestEnum {
    /// <summary>
    ///第一个枚举值必须默认为0
    /// </summary>
    [pbr::OriginalName("TESTENUM1")] _1 = 0,
    [pbr::OriginalName("TESTENUM2")] _2 = 1,
    [pbr::OriginalName("TESTENUM3")] _3 = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TestMsg : pb::IMessage<TestMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestMsg> _parser = new pb::MessageParser<TestMsg>(() => new TestMsg());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Heart.Message.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg(TestMsg other) : this() {
      _hasBits0 = other._hasBits0;
      a_ = other.a_;
      b_ = other.b_;
      c_ = other.c_;
      d_ = other.d_;
      e_ = other.e_;
      testFixed32_ = other.testFixed32_;
      testFixed64_ = other.testFixed64_;
      testSFixed32_ = other.testSFixed32_;
      testSFixed64_ = other.testSFixed64_;
      testBytes_ = other.testBytes_;
      testOptional_ = other.testOptional_;
      f_ = other.f_.Clone();
      g_ = other.g_.Clone();
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.H:
          H = other.H;
          break;
        case TestOneofOneofCase.I:
          I = other.I;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg Clone() {
      return new TestMsg(this);
    }

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 1;
    private float a_;
    /// <summary>
    ///规则七 成员类型 和 唯一编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "b" field.</summary>
    public const int BFieldNumber = 2;
    private int b_;
    /// <summary>
    ///变长编码 1-5字节 int32 int64  无符号 uint32 uint64  存负数 sint32 sint64 bool enum
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int B {
      get { return b_; }
      set {
        b_ = value;
      }
    }

    /// <summary>Field number for the "c" field.</summary>
    public const int CFieldNumber = 3;
    private long c_;
    /// <summary>
    ///C# long
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long C {
      get { return c_; }
      set {
        c_ = value;
      }
    }

    /// <summary>Field number for the "d" field.</summary>
    public const int DFieldNumber = 4;
    private string d_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string D {
      get { return d_; }
      set {
        d_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "e" field.</summary>
    public const int EFieldNumber = 5;
    private bool e_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool E {
      get { return e_; }
      set {
        e_ = value;
      }
    }

    /// <summary>Field number for the "testFixed32" field.</summary>
    public const int TestFixed32FieldNumber = 6;
    private uint testFixed32_;
    /// <summary>
    /// 固定字节 4字节 fixed32 fixed64 sfixed32 sfixed64
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TestFixed32 {
      get { return testFixed32_; }
      set {
        testFixed32_ = value;
      }
    }

    /// <summary>Field number for the "testFixed64" field.</summary>
    public const int TestFixed64FieldNumber = 7;
    private ulong testFixed64_;
    /// <summary>
    ///C# -ulong 它通常用来表示大于2的56次方的数 ，比uint64更有效 始终是8个字节
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TestFixed64 {
      get { return testFixed64_; }
      set {
        testFixed64_ = value;
      }
    }

    /// <summary>Field number for the "testSFixed32" field.</summary>
    public const int TestSFixed32FieldNumber = 8;
    private int testSFixed32_;
    /// <summary>
    ///C# - int 始终4个字节
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TestSFixed32 {
      get { return testSFixed32_; }
      set {
        testSFixed32_ = value;
      }
    }

    /// <summary>Field number for the "testSFixed64" field.</summary>
    public const int TestSFixed64FieldNumber = 9;
    private long testSFixed64_;
    /// <summary>
    ///C# - long 始终8个字节
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TestSFixed64 {
      get { return testSFixed64_; }
      set {
        testSFixed64_ = value;
      }
    }

    /// <summary>Field number for the "testBytes" field.</summary>
    public const int TestBytesFieldNumber = 10;
    private pb::ByteString testBytes_ = pb::ByteString.Empty;
    /// <summary>
    ///其他类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString TestBytes {
      get { return testBytes_; }
      set {
        testBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "testOptional" field.</summary>
    public const int TestOptionalFieldNumber = 11;
    private readonly static int TestOptionalDefaultValue = 0;

    private int testOptional_;
    /// <summary>
    ///规则八 特殊标识
    ///required 表示必须赋值的字段
    ///required float testRequired = 14;
    ///optional 表示可选字段
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TestOptional {
      get { if ((_hasBits0 & 1) != 0) { return testOptional_; } else { return TestOptionalDefaultValue; } }
      set {
        _hasBits0 |= 1;
        testOptional_ = value;
      }
    }
    /// <summary>Gets whether the "testOptional" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTestOptional {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "testOptional" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTestOptional() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "f" field.</summary>
    public const int FFieldNumber = 12;
    private static readonly pb::FieldCodec<int> _repeated_f_codec
        = pb::FieldCodec.ForInt32(98);
    private readonly pbc::RepeatedField<int> f_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///repeated 表示数组 List
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> F {
      get { return f_; }
    }

    /// <summary>Field number for the "g" field.</summary>
    public const int GFieldNumber = 13;
    private static readonly pbc::MapField<int, string>.Codec _map_g_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 106);
    private readonly pbc::MapField<int, string> g_ = new pbc::MapField<int, string>();
    /// <summary>
    ///map 表示字典 Dictionary
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, string> G {
      get { return g_; }
    }

    /// <summary>Field number for the "h" field.</summary>
    public const int HFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int H {
      get { return HasH ? (int) testOneof_ : 0; }
      set {
        testOneof_ = value;
        testOneofCase_ = TestOneofOneofCase.H;
      }
    }
    /// <summary>Gets whether the "h" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasH {
      get { return testOneofCase_ == TestOneofOneofCase.H; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "h" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearH() {
      if (HasH) {
        ClearTestOneof();
      }
    }

    /// <summary>Field number for the "i" field.</summary>
    public const int IFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string I {
      get { return HasI ? (string) testOneof_ : ""; }
      set {
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.I;
      }
    }
    /// <summary>Gets whether the "i" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasI {
      get { return testOneofCase_ == TestOneofOneofCase.I; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "i" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearI() {
      if (HasI) {
        ClearTestOneof();
      }
    }

    private object testOneof_;
    /// <summary>Enum of possible cases for the "testOneof" oneof.</summary>
    public enum TestOneofOneofCase {
      None = 0,
      H = 14,
      I = 15,
    }
    private TestOneofOneofCase testOneofCase_ = TestOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestOneofOneofCase TestOneofCase {
      get { return testOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTestOneof() {
      testOneofCase_ = TestOneofOneofCase.None;
      testOneof_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(A, other.A)) return false;
      if (B != other.B) return false;
      if (C != other.C) return false;
      if (D != other.D) return false;
      if (E != other.E) return false;
      if (TestFixed32 != other.TestFixed32) return false;
      if (TestFixed64 != other.TestFixed64) return false;
      if (TestSFixed32 != other.TestSFixed32) return false;
      if (TestSFixed64 != other.TestSFixed64) return false;
      if (TestBytes != other.TestBytes) return false;
      if (TestOptional != other.TestOptional) return false;
      if(!f_.Equals(other.f_)) return false;
      if (!G.Equals(other.G)) return false;
      if (H != other.H) return false;
      if (I != other.I) return false;
      if (TestOneofCase != other.TestOneofCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (A != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(A);
      if (B != 0) hash ^= B.GetHashCode();
      if (C != 0L) hash ^= C.GetHashCode();
      if (D.Length != 0) hash ^= D.GetHashCode();
      if (E != false) hash ^= E.GetHashCode();
      if (TestFixed32 != 0) hash ^= TestFixed32.GetHashCode();
      if (TestFixed64 != 0UL) hash ^= TestFixed64.GetHashCode();
      if (TestSFixed32 != 0) hash ^= TestSFixed32.GetHashCode();
      if (TestSFixed64 != 0L) hash ^= TestSFixed64.GetHashCode();
      if (TestBytes.Length != 0) hash ^= TestBytes.GetHashCode();
      if (HasTestOptional) hash ^= TestOptional.GetHashCode();
      hash ^= f_.GetHashCode();
      hash ^= G.GetHashCode();
      if (HasH) hash ^= H.GetHashCode();
      if (HasI) hash ^= I.GetHashCode();
      hash ^= (int) testOneofCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (A != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(A);
      }
      if (B != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(B);
      }
      if (C != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(C);
      }
      if (D.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(D);
      }
      if (E != false) {
        output.WriteRawTag(40);
        output.WriteBool(E);
      }
      if (TestFixed32 != 0) {
        output.WriteRawTag(53);
        output.WriteFixed32(TestFixed32);
      }
      if (TestFixed64 != 0UL) {
        output.WriteRawTag(57);
        output.WriteFixed64(TestFixed64);
      }
      if (TestSFixed32 != 0) {
        output.WriteRawTag(69);
        output.WriteSFixed32(TestSFixed32);
      }
      if (TestSFixed64 != 0L) {
        output.WriteRawTag(73);
        output.WriteSFixed64(TestSFixed64);
      }
      if (TestBytes.Length != 0) {
        output.WriteRawTag(82);
        output.WriteBytes(TestBytes);
      }
      if (HasTestOptional) {
        output.WriteRawTag(88);
        output.WriteInt32(TestOptional);
      }
      f_.WriteTo(output, _repeated_f_codec);
      g_.WriteTo(output, _map_g_codec);
      if (HasH) {
        output.WriteRawTag(112);
        output.WriteInt32(H);
      }
      if (HasI) {
        output.WriteRawTag(122);
        output.WriteString(I);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (A != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(A);
      }
      if (B != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(B);
      }
      if (C != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(C);
      }
      if (D.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(D);
      }
      if (E != false) {
        output.WriteRawTag(40);
        output.WriteBool(E);
      }
      if (TestFixed32 != 0) {
        output.WriteRawTag(53);
        output.WriteFixed32(TestFixed32);
      }
      if (TestFixed64 != 0UL) {
        output.WriteRawTag(57);
        output.WriteFixed64(TestFixed64);
      }
      if (TestSFixed32 != 0) {
        output.WriteRawTag(69);
        output.WriteSFixed32(TestSFixed32);
      }
      if (TestSFixed64 != 0L) {
        output.WriteRawTag(73);
        output.WriteSFixed64(TestSFixed64);
      }
      if (TestBytes.Length != 0) {
        output.WriteRawTag(82);
        output.WriteBytes(TestBytes);
      }
      if (HasTestOptional) {
        output.WriteRawTag(88);
        output.WriteInt32(TestOptional);
      }
      f_.WriteTo(ref output, _repeated_f_codec);
      g_.WriteTo(ref output, _map_g_codec);
      if (HasH) {
        output.WriteRawTag(112);
        output.WriteInt32(H);
      }
      if (HasI) {
        output.WriteRawTag(122);
        output.WriteString(I);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (A != 0F) {
        size += 1 + 4;
      }
      if (B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(B);
      }
      if (C != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(C);
      }
      if (D.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(D);
      }
      if (E != false) {
        size += 1 + 1;
      }
      if (TestFixed32 != 0) {
        size += 1 + 4;
      }
      if (TestFixed64 != 0UL) {
        size += 1 + 8;
      }
      if (TestSFixed32 != 0) {
        size += 1 + 4;
      }
      if (TestSFixed64 != 0L) {
        size += 1 + 8;
      }
      if (TestBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TestBytes);
      }
      if (HasTestOptional) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TestOptional);
      }
      size += f_.CalculateSize(_repeated_f_codec);
      size += g_.CalculateSize(_map_g_codec);
      if (HasH) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(H);
      }
      if (HasI) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(I);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestMsg other) {
      if (other == null) {
        return;
      }
      if (other.A != 0F) {
        A = other.A;
      }
      if (other.B != 0) {
        B = other.B;
      }
      if (other.C != 0L) {
        C = other.C;
      }
      if (other.D.Length != 0) {
        D = other.D;
      }
      if (other.E != false) {
        E = other.E;
      }
      if (other.TestFixed32 != 0) {
        TestFixed32 = other.TestFixed32;
      }
      if (other.TestFixed64 != 0UL) {
        TestFixed64 = other.TestFixed64;
      }
      if (other.TestSFixed32 != 0) {
        TestSFixed32 = other.TestSFixed32;
      }
      if (other.TestSFixed64 != 0L) {
        TestSFixed64 = other.TestSFixed64;
      }
      if (other.TestBytes.Length != 0) {
        TestBytes = other.TestBytes;
      }
      if (other.HasTestOptional) {
        TestOptional = other.TestOptional;
      }
      f_.Add(other.f_);
      g_.MergeFrom(other.g_);
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.H:
          H = other.H;
          break;
        case TestOneofOneofCase.I:
          I = other.I;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            A = input.ReadFloat();
            break;
          }
          case 16: {
            B = input.ReadInt32();
            break;
          }
          case 24: {
            C = input.ReadInt64();
            break;
          }
          case 34: {
            D = input.ReadString();
            break;
          }
          case 40: {
            E = input.ReadBool();
            break;
          }
          case 53: {
            TestFixed32 = input.ReadFixed32();
            break;
          }
          case 57: {
            TestFixed64 = input.ReadFixed64();
            break;
          }
          case 69: {
            TestSFixed32 = input.ReadSFixed32();
            break;
          }
          case 73: {
            TestSFixed64 = input.ReadSFixed64();
            break;
          }
          case 82: {
            TestBytes = input.ReadBytes();
            break;
          }
          case 88: {
            TestOptional = input.ReadInt32();
            break;
          }
          case 98:
          case 96: {
            f_.AddEntriesFrom(input, _repeated_f_codec);
            break;
          }
          case 106: {
            g_.AddEntriesFrom(input, _map_g_codec);
            break;
          }
          case 112: {
            H = input.ReadInt32();
            break;
          }
          case 122: {
            I = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            A = input.ReadFloat();
            break;
          }
          case 16: {
            B = input.ReadInt32();
            break;
          }
          case 24: {
            C = input.ReadInt64();
            break;
          }
          case 34: {
            D = input.ReadString();
            break;
          }
          case 40: {
            E = input.ReadBool();
            break;
          }
          case 53: {
            TestFixed32 = input.ReadFixed32();
            break;
          }
          case 57: {
            TestFixed64 = input.ReadFixed64();
            break;
          }
          case 69: {
            TestSFixed32 = input.ReadSFixed32();
            break;
          }
          case 73: {
            TestSFixed64 = input.ReadSFixed64();
            break;
          }
          case 82: {
            TestBytes = input.ReadBytes();
            break;
          }
          case 88: {
            TestOptional = input.ReadInt32();
            break;
          }
          case 98:
          case 96: {
            f_.AddEntriesFrom(ref input, _repeated_f_codec);
            break;
          }
          case 106: {
            g_.AddEntriesFrom(ref input, _map_g_codec);
            break;
          }
          case 112: {
            H = input.ReadInt32();
            break;
          }
          case 122: {
            I = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TestMsg2 : pb::IMessage<TestMsg2>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestMsg2> _parser = new pb::MessageParser<TestMsg2>(() => new TestMsg2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestMsg2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Heart.Message.MessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg2(TestMsg2 other) : this() {
      testMsg_ = other.testMsg_ != null ? other.testMsg_.Clone() : null;
      testEnum_ = other.testEnum_;
      testMsg2_ = other.testMsg2_ != null ? other.testMsg2_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg2 Clone() {
      return new TestMsg2(this);
    }

    /// <summary>Field number for the "testMsg" field.</summary>
    public const int TestMsgFieldNumber = 1;
    private global::Heart.Message.TestMsg testMsg_;
    /// <summary>
    ///规则十一 嵌套  默认为null 使用时需要new
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Heart.Message.TestMsg TestMsg {
      get { return testMsg_; }
      set {
        testMsg_ = value;
      }
    }

    /// <summary>Field number for the "testEnum" field.</summary>
    public const int TestEnumFieldNumber = 2;
    private global::Heart.Message.TestEnum testEnum_ = global::Heart.Message.TestEnum._1;
    /// <summary>
    ///规则十二 引用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Heart.Message.TestEnum TestEnum {
      get { return testEnum_; }
      set {
        testEnum_ = value;
      }
    }

    /// <summary>Field number for the "testMsg2" field.</summary>
    public const int TestMsg2_FieldNumber = 3;
    private global::Heart.Message.TestMsg2 testMsg2_;
    /// <summary>
    ///规则十三 引用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Heart.Message.TestMsg2 TestMsg2_ {
      get { return testMsg2_; }
      set {
        testMsg2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestMsg2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestMsg2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TestMsg, other.TestMsg)) return false;
      if (TestEnum != other.TestEnum) return false;
      if (!object.Equals(TestMsg2_, other.TestMsg2_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (testMsg_ != null) hash ^= TestMsg.GetHashCode();
      if (TestEnum != global::Heart.Message.TestEnum._1) hash ^= TestEnum.GetHashCode();
      if (testMsg2_ != null) hash ^= TestMsg2_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (testMsg_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TestMsg);
      }
      if (TestEnum != global::Heart.Message.TestEnum._1) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TestEnum);
      }
      if (testMsg2_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TestMsg2_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (testMsg_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TestMsg);
      }
      if (TestEnum != global::Heart.Message.TestEnum._1) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TestEnum);
      }
      if (testMsg2_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TestMsg2_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (testMsg_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestMsg);
      }
      if (TestEnum != global::Heart.Message.TestEnum._1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TestEnum);
      }
      if (testMsg2_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestMsg2_);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestMsg2 other) {
      if (other == null) {
        return;
      }
      if (other.testMsg_ != null) {
        if (testMsg_ == null) {
          TestMsg = new global::Heart.Message.TestMsg();
        }
        TestMsg.MergeFrom(other.TestMsg);
      }
      if (other.TestEnum != global::Heart.Message.TestEnum._1) {
        TestEnum = other.TestEnum;
      }
      if (other.testMsg2_ != null) {
        if (testMsg2_ == null) {
          TestMsg2_ = new global::Heart.Message.TestMsg2();
        }
        TestMsg2_.MergeFrom(other.TestMsg2_);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (testMsg_ == null) {
              TestMsg = new global::Heart.Message.TestMsg();
            }
            input.ReadMessage(TestMsg);
            break;
          }
          case 16: {
            TestEnum = (global::Heart.Message.TestEnum) input.ReadEnum();
            break;
          }
          case 26: {
            if (testMsg2_ == null) {
              TestMsg2_ = new global::Heart.Message.TestMsg2();
            }
            input.ReadMessage(TestMsg2_);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (testMsg_ == null) {
              TestMsg = new global::Heart.Message.TestMsg();
            }
            input.ReadMessage(TestMsg);
            break;
          }
          case 16: {
            TestEnum = (global::Heart.Message.TestEnum) input.ReadEnum();
            break;
          }
          case 26: {
            if (testMsg2_ == null) {
              TestMsg2_ = new global::Heart.Message.TestMsg2();
            }
            input.ReadMessage(TestMsg2_);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TestMsg3 : pb::IMessage<TestMsg3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestMsg3> _parser = new pb::MessageParser<TestMsg3>(() => new TestMsg3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestMsg3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Heart.Message.MessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg3(TestMsg3 other) : this() {
      testMsg2_ = other.testMsg2_ != null ? other.testMsg2_.Clone() : null;
      testMsg3_ = other.testMsg3_ != null ? other.testMsg3_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg3 Clone() {
      return new TestMsg3(this);
    }

    /// <summary>Field number for the "testMsg2" field.</summary>
    public const int TestMsg2FieldNumber = 1;
    private global::Heart.Message.TestMsg2 testMsg2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Heart.Message.TestMsg2 TestMsg2 {
      get { return testMsg2_; }
      set {
        testMsg2_ = value;
      }
    }

    /// <summary>Field number for the "testMsg3" field.</summary>
    public const int TestMsg3_FieldNumber = 2;
    private global::Heart.Message.TestMsg3 testMsg3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Heart.Message.TestMsg3 TestMsg3_ {
      get { return testMsg3_; }
      set {
        testMsg3_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestMsg3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestMsg3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TestMsg2, other.TestMsg2)) return false;
      if (!object.Equals(TestMsg3_, other.TestMsg3_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (testMsg2_ != null) hash ^= TestMsg2.GetHashCode();
      if (testMsg3_ != null) hash ^= TestMsg3_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (testMsg2_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TestMsg2);
      }
      if (testMsg3_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TestMsg3_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (testMsg2_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TestMsg2);
      }
      if (testMsg3_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TestMsg3_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (testMsg2_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestMsg2);
      }
      if (testMsg3_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestMsg3_);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestMsg3 other) {
      if (other == null) {
        return;
      }
      if (other.testMsg2_ != null) {
        if (testMsg2_ == null) {
          TestMsg2 = new global::Heart.Message.TestMsg2();
        }
        TestMsg2.MergeFrom(other.TestMsg2);
      }
      if (other.testMsg3_ != null) {
        if (testMsg3_ == null) {
          TestMsg3_ = new global::Heart.Message.TestMsg3();
        }
        TestMsg3_.MergeFrom(other.TestMsg3_);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (testMsg2_ == null) {
              TestMsg2 = new global::Heart.Message.TestMsg2();
            }
            input.ReadMessage(TestMsg2);
            break;
          }
          case 18: {
            if (testMsg3_ == null) {
              TestMsg3_ = new global::Heart.Message.TestMsg3();
            }
            input.ReadMessage(TestMsg3_);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (testMsg2_ == null) {
              TestMsg2 = new global::Heart.Message.TestMsg2();
            }
            input.ReadMessage(TestMsg2);
            break;
          }
          case 18: {
            if (testMsg3_ == null) {
              TestMsg3_ = new global::Heart.Message.TestMsg3();
            }
            input.ReadMessage(TestMsg3_);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
